version: "3.8"

services:
    app:
        build: .
        image: 3npm:latest
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
        depends_on:
            - db
        env_file:
            - .env

    db:
        image: mongo:7.0.12
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    mongo-express:
        image: mongo-express:1.0.2
        depends_on:
            - db
        environment:
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_MONGODB_DATABASE: ${MONGO_DATABASE}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: ${MONGO_URI}
            ME_CONFIG_BASICAUTH: false
        ports:
            - "8081:8081"